### PR TITLE
Added camera and sonar sensor to gazebo urdf

### PR DESCRIPTION
**Pull request by ferherranz**

### CODE REVIEW

**Comment by vrabaud** [comment]
@keulYSMB  , any feedback ? I know the cameras are in here:
https://github.com/ros-naoqi/nao_robot/blob/master/nao_description/urdf/naoV40_generated_urdf/nao_sensors.xacro#L174
but that does not include the whole parametrization.

**Comment by keulYSMB** [comment]
Makes no sense, the naoGazebo.xacro file is really ol there is no sensor in it. 
The last I pushed contained cameras and sonar tuned according to measurement on the real robot. 
I'll check that later and keep you updated but I don't think that I have this file outside Aldebaran.

**Comment by keulYSMB** [comment]
It seems that the cameras, the depth camera and the sonar are still in this xacro : 
https://github.com/ros-nao/nao_robot_to_delete/blob/master/nao_description/urdf/naoV40_generated_urdf/naoGazebo.xacro
I don't get why they're not on the one in ros-naoqi organization. The values seem to be the right one. I'll do a pull request shortly after testing.

**Comment by ferherranz** [comment]
I added the sensors because I followed this tutorial (https://github.com/ros-naoqi/nao_virtual/blob/master/nao_gazebo_plugin/README.rst) but I couldn't get the topics from the sensors.

**Comment by keulYSMB** [comment]
I didn't have time to perform testing yesterday, I'll do it today and keep you updated.

**Comment by keulYSMB** [comment]
I pushed a fix based on what is https://github.com/ros-nao/nao_robot_to_delete/blob/master/nao_description/urdf/naoV40_generated_urdf/naoGazebo.xacro

I launched roslaunch nao_gazebo_plugin nao_gazebo_plugin_H25.launch 
The sensors are working on my computer, can you give it a try and let me know ?

Thus the robot is not stable we'll have to figure that out

**Comment by ferherranz** [comment]
Yeap, the sensors are also working on my computer.

I've also noticed that the robot isn't stable...

**Comment by vrabaud** [comment]
I guess that requires a new release. How about this robot instability ?

**Comment by keulYSMB** [comment]
The robot seems to be oscilating more than before. Especially at the beginning when the robot is spawned. I didn't have time to investigate yet. We should definitely track what is different from the previous more stable version. I'll focus on it as soon as I have time to allocate to this project.

**Comment by vrabaud** [comment]
All that seems up-to-date upstream now (no changes are shown if I merge your commits), so closing. Very sorry for the delay, but that got fixed 6 months ago.

**Pull request closed without merging**
