### PR TITLE
fix FSR sensor frame

### PR DESCRIPTION
**Pull request by hakuturu583**
Left foot front left FSR sensor was on a right  foot front left FSR sensor position.

### CODE REVIEW

**Comment by hakuturu583** [comment]
Yes, I think so.

**Comment by nlyubova** [comment]
@mikaelarguedas, I've merge it if you do not mind

**Comment by nlyubova** [comment]
@hakuturu583 thank you!

**Comment by hakuturu583** [comment]
@nlyubova Thank you for merging merging my pull request!!!

**Pull request merged**
